'use server';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { decrementHeart, getOrCreateUserProgress, getUserPremiumStatus, resetHearts, updateUserProgress } from '@/db/queries';
async function getUserId() { const sb = createClient(); const { data: { user }, error } = await sb.auth.getUser(); if (error || !user) throw new Error('Unauthorized'); return user.id; }
export const finishLesson = async (lessonId: string) => { try { const userId = await getUserId(); const progress = await getOrCreateUserProgress(userId); const newPoints = progress.points + 10; const lastActive = progress.last_active ? new Date(progress.last_active) : null; const today = new Date(); const isSameDay = lastActive?.toDateString() === today.toDateString(); let newStreak = progress.streak; if (!isSameDay) { newStreak += 1; } await updateUserProgress(userId, { points: newPoints, streak: newStreak, last_active: today.toISOString() }); revalidatePath('/learn'); revalidatePath('/dashboard'); return { success: true }; } catch (error) { console.error('FINISH_LESSON_ERROR', error); return { error: 'Failed to finish lesson.' }; } };
export const submitAnswer = async (lessonId: string, exerciseId: string, answer: string, isCorrect: boolean) => { try { const userId = await getUserId(); const isPremium = await getUserPremiumStatus(userId); const progress = await getOrCreateUserProgress(userId); if (!isCorrect && !isPremium) { if (progress.hearts === 0) { return { error: 'no_hearts' }; } const updated = await decrementHeart(userId); return { isCorrect: false, hearts: updated?.hearts ?? 0 }; } return { isCorrect: true, hearts: progress.hearts }; } catch (error) { console.error('SUBMIT_ANSWER_ERROR', error); return { error: 'Something went wrong.' }; } };
export const refillHearts = async () => { try { const userId = await getUserId(); const isPremium = await getUserPremiumStatus(userId); if (!isPremium) { return { error: 'Only Pro members can refill hearts instantly.' }; } await resetHearts(userId); revalidatePath('/learn'); revalidatePath('/shop'); return { success: true }; } catch (error) { console.error('REFILL_HEARTS_ERROR', error); return { error: 'Failed to refill hearts.' }; } };
export const selectCourse = async (courseId: string) => { try { const userId = await getUserId(); await updateUserProgress(userId, { active_course_id: courseId }); revalidatePath('/learn'); return { success: true }; } catch (error) { return { error: 'Failed to select course.' }; } };
